### ISSUE TITLE
Add exception for Mage Training Arena items

### ISSUE THREAD

**Issue by nsilvestri** [CreativeTechGuy/no-bad-alchs#5]
Mage training arena items are always bad alchs, so the items are hidden. However, this can be confusing, as these items aren't typical items and the failsafe that this plugin acts as is often not consciously being considered, leading to people unaware that this plugin is blocking the entire MTA alchemy room.

**Comment by CreativeTechGuy** [comment]
Good callout! I'll update that ASAP.

**Comment by CreativeTechGuy** [comment]
Thanks for the report! It's currently pending RuneLite Plugin Hub approval. You can track that here: https://github.com/runelite/plugin-hub/pull/5472
