### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by Sebastipole** [CreativeTechGuy/no-bad-alchs#6]
Plugin is no longer hiding items while alching.

Inventory while high alching currently.
![image](https://github.com/CreativeTechGuy/no-bad-alchs/assets/76943354/51533451-4417-47eb-befc-faf12460319f)

What should be happening: 
All of those inventory items should be hidden while high alching.

Plugin settings
![image](https://github.com/CreativeTechGuy/no-bad-alchs/assets/76943354/2ed49054-35e4-44f0-b60f-dd9710f0831e)

**Comment by Sebastipole** [comment]
I worked out that there is a conflict with another plugin, "Remaining Casts".

For some reason, if you have "Show on menu tooltip" enabled in the conflicting plugin, it breaks your plugin, No bad Alch's.

Link to the plugin
https://runelite.net/plugin-hub/show/remaining-casts

**Comment by CreativeTechGuy** [comment]
Hi @Sebastipole. Sorry for the delay. I have found the issue and have a workaround for the time being. I've also reached out to the other developer to let them know the root cause and gave a suggestion to avoid this issue in the future with other plugins.

I'll get a release out for No Bad Alchs ASAP!

**Comment by CreativeTechGuy** [comment]
Here's the release if you would like to track it: https://github.com/runelite/plugin-hub/pull/6259

**Comment by Sebastipole** [comment]
> Here's the release if you would like to track it: [runelite/plugin-hub#6259](https://github.com/runelite/plugin-hub/pull/6259)

Thank you mate, love this plugin, honestly should be in the base game.
