### ISSUE TITLE
Items stay hidden after alch until clicking

### ISSUE THREAD

**Issue by Shermss** [CreativeTechGuy/no-bad-alchs#7]
Specifically when using F-Keys to swap back to inventory (F1/1 in my case) after alching at least once, whereas clicking the inventory button unhides the items.

Clicking anywhere causes items to return

![vlc_2024-08-01_17-12-12](https://github.com/user-attachments/assets/12a220b0-0c93-40b6-9445-efbf8e035be0)

While I understand why this is the case, I would appreciate if F-Keys were supported too.

**Comment by CreativeTechGuy** [comment]
Aww dang it. This worked before. It looks like I broke this when fixing #6 (plugin compatibility).

I am getting a fix out for it ASAP.

**Comment by CreativeTechGuy** [comment]
You can track the release of the new version here: https://github.com/runelite/plugin-hub/pull/6392
